# Generated by Django 5.0.4 on 2024-04-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_category_alter_item_reserved_by_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reserved',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
