# Generated by Django 5.0.4 on 2024-04-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_facebook_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='facebook_profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='google_profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
