# Generated by Django 5.0.4 on 2024-04-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_facebook_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='facebook_profile_image_url',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='google_profile_image_url',
        ),
    ]
